# purpose of integrating with circleci whenever pushed to release branch, it triggers:
# - build docker image
# - upload docker image into google cloud
# - update the tag in ketalk-k8s-config

version: 2.1
orbs:
  go: circleci/go@1.7
  gcp-gcr: circleci/gcp-gcr@0.13
  jq: circleci/jq@2

jobs:
  publish:
    docker:
      - image: cimg/python:2.7.17
    steps:
      - jq/install
      - setup_remote_docker
      - gcp-gcr/gcr-auth
      # create new docker image
      - checkout
      - run: gcloud config set project ${GOOGLE_PROJECT_ID}
      - run: echo 'export SERVICE_VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run: echo 'export SERVICE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
      - run: docker build -t gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:${SERVICE_VERSION} .
      - run: docker push gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:${SERVICE_VERSION}
      - run: gcloud container images add-tag --quiet gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:${SERVICE_VERSION} gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:latest
      - run:
          name: ssh keychain
          command: ssh-keyscan github.com
      - run:
          name: check ssh
          command: ls ~/.ssh
      - run:
          name: pre-auth github.com
          command: |
            mkdir -p ~/.ssh && \
            touch ~/.ssh/known_hosts && \
            chmod 600 ~/.ssh/known_hosts && \
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: clone ketalk-k8s-config
          command: git clone -b master git@github.com:Kalomidin/ketalk-k8s-config.git appcfg
      - run:
          name: give write permissions
          command: sudo chmod +x appcfg/.circleci/promote.sh appcfg/.circleci/update-version.sh
      - run:
          name: update version in ketalk-k8s-config
          command: BRANCH_NAME=master appcfg/.circleci/promote.sh

workflows:
  continuous-integration:
    jobs:
      - publish:
          context:
            - gcloud
          filters:
            branches:
              only: release